# Generated by Django 4.1 on 2022-08-31 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("JoinUPTest", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="CodePhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="email_validated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_validated",
            field=models.BooleanField(default=False),
        ),
    ]
