# Generated by Django 4.1 on 2022-09-03 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("JoinUPTest", "0003_codeemail_user_codephone_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("recipe", "SMS"), ("image-comparative", "e-mail")],
                        max_length=20,
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="JoinUPTest.user",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="codephone",
            name="user",
        ),
        migrations.DeleteModel(
            name="CodeEmail",
        ),
        migrations.DeleteModel(
            name="CodePhone",
        ),
    ]
