# Generated by Django 4.1 on 2022-09-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("JoinUPTest", "0004_activationcode_remove_codephone_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activationcode",
            name="code",
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name="activationcode",
            name="type",
            field=models.CharField(
                choices=[("SMS", "SMS"), ("e-mail", "e-mail")], max_length=20
            ),
        ),
    ]
