name: Django CI PROD

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    environment: master
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8.1]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install celery
        pip install -r requirements.txt
    - name: Run Tests
      env: 
        ACTIVATION_PROCESS: False
        CELERY_TASK_ALWAYS_EAGER: True
      run: |
        python manage.py test
